from django.urls import path, include
from .views import users, email, friend, group, sysmsg, file, msg
urlpatterns = [
    path('user/register', users.register),
    path('user/login', users.login),
    path('user/logout', users.logout),
    path('user/modify', users.modify),
    path('user/cancel', users.cancel),
    path('user/search', users.search),
    path('user/send_mail', email.send_mailcode),
    path('user/verify_mail', email.verify_mailcode),
    path('user/avatar', users.avatar),
    path('friend/list', friend.friend_list),
    path('friend/delete', friend.friend_delete),
    path('friend/apply', friend.apply),
    path('group/search', group.search),
    path('group/create', group.create),
    path('group/delete', group.group_delete),
    path('group/list', group.group_list),
    path('group/join', group.join),
    path('group/leave', group.leave),
    path('group/kick_user', group.kick_user),
    path('group/set_role', group.set_role),
    path('group/info', group.info),
    path('group/avatar', group.avatar),
    path('group/announce', group.announce),
    path('group/announcements', group.announcements),
    path('group/preference', group.preference),
    path('group/modify', group.modify),
    path('sysmsg/handle', sysmsg.handle),
    path('sysmsg/fetch', sysmsg.fetch),
    path('file/upload', file.upload),
    path('file/download', file.download),
    path('msg/fetch', msg.fetch),
    path('msg/ack', msg.ack),
    path('msg/recall', msg.recall),
    path('msg/delete', msg.msg_delete),
    path('msg/forward', msg.forward),
    path('msg/translate', msg.translate),
]
